let suggestions = [
    "Incognito",
    "Inflopnito",
    "Vys",
    "YouTube",
    "YouTuber",
    "YouTube Channel",
    "Blogger",
    "Bollywood",
    "Vlogger",
    "The Rat",
    "Facebook",
    "Freelancer",
    "Facebook Page",
    "Designer",
    "Developer",
    "Web Designer",
    "Web Developer",
    "Login Form in HTML & CSS",
    "How to learn HTML & CSS",
    "How to learn JavaScript",
    "How to become a Freelancer",
    "How to become a Web Designer",
    "How to start a Gaming Channel",
    "How to start a YouTube Channel",
    "What does HTML stand for?",
    "What does CSS stand for?",
];